# Generated by Django 5.2.17 on 2026-09-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role_alter_user_age_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
