# Generated by Django 5.2.17 on 2026-09-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_rename_userinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
